version: '3'

services:
  app:
    image: asia-southeast2-docker.pkg.dev/zeta-embassy-387512/ifn/ifn-transport
    container_name: backend-infra-app
    build: .
    ports:
      - 5000:5000
    env_file:
      - service/.env
    restart: always