version: '3'

services:
  app:
    image: yankyhermawan/backend-infra
    container_name: backend-infra-app
    build: .
    ports:
      - 5000:5000
    env_file:
      - service/.env
    restart: always